name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - elixir: 1.12.0
            otp: 22.3
          - elixir: 1.15.2
            otp: 25.3
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: _build/test
          key: build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
      - name: Install dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile
      - name: Compile
        run: mix compile --warnings-as-errors
      - name: Dialyzer
        run: mix dialyzer --halt-exit-status
      - name: Run tests
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
